version: '3.7'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: teste-transfeera-tamalu:latest
    ports:
      - '3000:3000'
    environment:
      PORT: '3000'
      POSTGRES_DB_URL: 'postgresql://postgres:postgres@db:5432/postgres'
    depends_on:
      db:
        condition: service_started
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
